
name: 'floranow'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
#test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  erp_source: 'erp_prod_rds'
  mkp_source: 'marketplace_prod_master'


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  floranow:
    # Applies to all files under models/example/
    1_staging:
        +enabled: true
        +materialized: view
        +schema: stg
      

    2_marts:
      +enabled: true
      +materialized: table
      +schema: dwh
      dim_date:
        +materialized: view


