With source as (
 select * from {{ source('erp_prod', 'invoices') }}
)
select 
            --PK
                i.id as invoice_header_id,
            --FK
                --parent_invoice_id,
                customer_id,
                proof_of_delivery_id,
                in_shop_order_number,
                purchase_order_number,
                odoo_id,
                sub_customer_id,

                financial_administration_id,

                case --financial ID
                    when i.financial_administration_id = 1 then 'KSA'
                    when i.financial_administration_id = 2 then 'UAE'
                    when i.financial_administration_id = 3 then 'Jordan'
                    when i.financial_administration_id = 4 then 'kuwait'
                    when i.financial_administration_id = 5 then 'Qatar'
                    when i.financial_administration_id = 6 then 'Bulk'
                    when i.financial_administration_id = 7 then 'Internal'
                    else 'check_my_logic'
                end as financial_administration,


                printed_by_id,
                --deleted_by,
                canceled_by_id,
                --paid_by,
                --finalized_by,
               -- void_by,
                voided_by_id,
                created_by,

            --dim
                --date
                canceled_at, --This date indicates when the invoice record was created in your system. This date is usually automatically generated by the system at the moment when the invoice is created. It's important for record-keeping and tracking when the invoice was initially generated.
                created_at as invoice_header_created_at,  --proforma_at,
                printed_at as invoice_header_printed_at,  --invoiced_at, --DispatchDate  --This is the date when the invoice was printed and sent to the client. This date is critical as it might be used to start the payment term clock, especially if your terms are something like "Net 30 days from receipt of invoice". This date can be seen as the official invoice date from the customer's perspective, as it signifies when they received the invoice.
                updated_at,
                signed_at,
               -- finalized_at,
                last_payment_at,
                due_date,
                voided_at,
                last_send_email_at,
                items_collection_date,
                paid_at,
                deleted_at,
                case
                when i.status = 0 then "Draft"
                when i.status = 1 then "signed"
                when i.status = 2 then "Open"
                when i.status = 3 then "Printed"
                when i.status = 6 then "Closed"
                when i.status = 7 then "Canceled"
                when i.status = 8 then "Rejected"
                when i.status = 9 then "voided"
                when i.status is null then ""
                else "check_my_logic"
                end as invoice_header_status,


                source_system, --FLORANOW_ERP, FLORISOFT, ODOO


                --dim
                --creation_condition,
                language,
                number,
                currency,
                case 
                when i.invoice_type = 1 then 'credit note' 
                when i.invoice_type = 0 then 'invoice'
                else 'check' end as invoice_header_type,
                items_collection_method,
                items_source_type,
                generation_type,
                source_type, -- EXTERNAL, INTERNAL
                

                case 
                    when i.invoice_type = 1 and i.generation_type ='AUTO' then 'Credit Note - AUTO'
                    when i.invoice_type = 1 and i.generation_type ='MANUAL' then 'Credit Note - MANUAL'
                    when i.invoice_type = 0 and i.generation_type ='MANUAL' then 'Invoice - MANUAL'
                    when i.invoice_type = 0 and i.generation_type ='AUTO' then 'Invoice - AUTO'
                    else null
                end as record_type,


        --fct
            remaining_amount,
            tax_rate,
            prev_remaining_amount,
            total_tax,
            total_amount,
            paid_amount,
            discount_amount,
            price_without_discount,
            total_amount - total_tax as total_amount_without_tax,



current_timestamp() as ingestion_timestamp

 
from source as i 

where i.deleted_at IS NULL
